### ISSUE TITLE
format '(i)' not accepted by gfortran

### ISSUE THREAD

**Issue by wvermin** [jdonners/gabriel#3]
Line 133 of gabriel.f90:

read(verbosity,'(i)')v

is not accepted by gfortran. The following is accepted:

read(verbosity,*)v

**Comment by szaghi** [comment]
Dear @wvermin 

I think that it is because the standard currently require to specify the field-with for integer, for example a standard compliant format should be something like

``` fortran
read(verbosity, '(i11)') v ! 11 digits integer
```

Your accepted call is using list directly that is probably more robust than and explicit integer-formatted read.

My best regards.

**Comment by jdonners** [comment]
Hi Willem,

thanks for the reminder (nice to read that it's actually being tested:). I did fix the read statement, but hadn't yet pushed it to github (that's done now). I decided to use the field-width and an err-label (ugh!), to make it more robust: it now compiles with gfortran and it doesn't fail if GABRIEL_VERBOSE is empty or non-sensical.
